olin/studentgovernment

student_government_bylaws.md

Approved by the Student Government on September 3rd.

Published amendment to add resignation procedures.

---

README.md
student_government_bylaws.md
student_government_constitution.md

No text was changed during this commit. The markdown display on Github
should be pixel-identical after this change.
(Compare https://github.com/MattWis/studentgovernment/tree/whitespace with https://github.com/olin/studentgovernment)

Keep line lengths short, so diffs look better.

---

student_government_bylaws.md

**BA-1516-004:** An Student Government By-Law amendment to increase the club spending limit on food from $2 per person per event to $3 per person per event.

BA-1516-004: Increase Spending Limits on Food

---

student_government_bylaws.md

**BA-1516-005:** An amendment to strike from the By-Laws Article 9 Section 3 requiring the creation of Funding Guidelines in Fall 2015.

BA-1516-005: No Funding Guidelines

---

student_government_bylaws.md

**BA-1516-007:** An amendment to reduce the time to volunteer for faculty and operational committees from an arbitrary 6 days to a more reasonable 3 days.

BA-1516-007: Committee Appointment Timeline

---

student_government_bylaws.md

**BA-1516-008:** An amendment refining the SERV By-Laws around Service Student Groups, Service Pursuits, and the role of the Assistant Director.

BA-1516-008: SERV By-Law Refinements

---

student_government_bylaws.md

These are easier to comment/iterate on when they're pull requests.

BA-1516-009: General Refinements

---

student_government_bylaws.md

These are easier to comment/iterate on when they're pull requests.

BA-1516-011: Change the By-Laws to Present Tense

---

student_government_bylaws.md

Amends BA-1516-010 such that it only refines the role of Class Representative and broadens the scope of the Class Funds.

Amendment 1 to BA-1516-010

---

student_government_bylaws.md

These are easier to comment/iterate on when they're pull requests.

BA-1516-010: Representation on CORe

---

student_government_bylaws.md

On March 21, 2016, the Student Government agreed to change the the Student Government By-Laws to present tense. Somehow the pull request did not contain all of the necessary changes. This pull request fixes that error and completes the process of converting the By-Laws. Since the intent of BA-1516-011 was clear and agreed upon, I am submitting and merging this pull request without further approval from the Student Government. If there are any objections, please feel free to reach out to me.

Completing BA-1516-011: Changing the By-Laws to Present Tense

---

README.md
student_government_bylaws.md

**BA-1617-002**: An amendment assigning the Director of CCO the responsibility of maintaining the List of Student Groups and Administration Committees.

BA-1617-002: Assigned DCCO the Student Groups List

---

README.md
student_government_bylaws.md

**BA-1617-001:** An amendment renaming the CORe Representative to Operations to Representative for Student Services.

BA-1617-001: Renaming Operations to Student Services

---

README.md
student_government_bylaws.md

**BA-1617-007:** An amendment clarifying various parts of the election process as proposed by Mitch in issue #19.

BA-1617-007: Election process clarifications

---

README.md
student_government_bylaws.md

**BA-1617-006:** An amendment changing the audit process such that the Chair and the Vice Chair of the Honor Board can conduct the audit of the Honor Board themselves.
_Proposed by the Honor Board_

BA-1617-006: The Honor Board conducts separate audits

---

README.md
student_government_bylaws.md

**BA-1617-004:** An amendment moving the timing of the Student Government Audits to the end of the semester instead of mid-semester.
_Proposed by the Honor Board_

BA-1617-004: Audits occur at the end of each semester

---

README.md
student_government_bylaws.md

BA-1718-002: An amendment to change the definition of the Student Body from students who "plan to graduate from Olin College" to "all currently enrolled students of Olin College."

BA-1718-002: Changing definition of Student Body

---

student_government_constitution.md

The links were broken in the constitution, this pull request fixes it.

Fix links from broken /ca-working branch to /master

---

README.md

featuring the worst possible default branch name.
Hoping to add the BAs passed on 05/06 and also resolve that one of the amendments from 17-18 was between ones from 16-17 (unless that was intentional for some reason).

Added 1819 BAs and fixed ordering in README

---

README.md
bylaws.md

Google drive and GitHub are great tools! Let's codify that we like using them in a way that lets us be flexible while still being transparent.

BA-1920-003 Generalized wording on the forms transparency documents can take. 

---

README.md
bylaws.md

Add an additional election cycle in the winter - this one covers the honor board positions.

BA-1920-005: Add winter elections

---

README.md
bylaws.md

The current audit process has not really been used, which seems like a pretty bad practice. I tried to figure out how to implement the audit process this semester but honestly just got really confused reading the by-laws about how to make it happen. This amendment is an attempt to create something clear and low-overhead that is still useful.
I don't know if this is a perfect process, but I'd like to codify something to then iterate on. Please reach out to me with feedback!

BA-1920-007 Tried to create more clearly outlined audit process.

---

README.md
bylaws.md

Added charter requirements to student group classifications as requested by [Issue 20](https://github.com/olin/studentgovernment/issues/20). Seeking feedback from CCO leadership.

BA-1920-010: Added charter requirements to student group classifications.

---

README.md
constitution.md

PR to be voted on for approval at February 2020 Town Hall.

CA-1920-001: Update constitution sunset to 2022.

---

README.md
constitution.md

Removed need for Pres. acknowledgement for SG voting power to carry to assistant director as noted in issue [66](https://github.com/olin/studentgovernment/issues/66)

CA-1920-005: Automatically defer power to assistant director when Committee Director is not present. 

---

README.md
constitution.md

Reasoning in Issue [69](https://github.com/olin/studentgovernment/issues/69). Want to update by-law definitions.

CA-1920-006: Generalize definition of by-laws.

---

README.md
bylaws.md

Title ought to be self-explanatory, reflecting change passed at town hall on 2/12. Here's the [issue](https://github.com/olin/studentgovernment/issues/84)

BA-1920-012: Changed every instance of by-law to bylaw in the By-laws/bylaws

---

bylaws.md

Article 2, Section 1 Amendment
Article 2, Section 3 Amendment
Article 11, Section 3 Amendment

Updated STaR Rep Full Form
